name: flutter_map_training
description: Flutter application with google maps support for mobile and web platforms

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

  firebase_core: ^2.32.0
  google_sign_in: ^6.3.0
  firebase_auth: ^4.1.5
  flutter_secure_storage: ^6.0.0
  cloud_firestore: ^4.17.5
  logging: ^1.1.0

  #state
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  #network
  connectivity_plus: ^6.0.3
  dio: ^5.4.0

  #maps
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.14+3
  geolocator: ^12.0.0
  intl: ^0.17.0
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.3.0
  battery_plus: ^6.2.0
  shared_preferences: ^2.2.2
  flutter_foreground_task: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  geolocator_android: ^4.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/evolve_logo.png"
  adaptive_icon_foreground: "assets/icons/evolve_logo.png"
  adaptive_icon_background: "#FFFFFF"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/map_type_normal.png
    - assets/images/map_type_satellite.png
    - assets/icons/google_logo.svg
    - assets/icons/logonobg.png
